import type { Metadata } from "next";
import { Google_Sans_Flex, Bebas_Neue, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/navbar";
import SubNav from "./components/subnav";

const googleSansFlex = Google_Sans_Flex({
  subsets: ['latin'],
  variable: '--font-google-sans-flex',
})

const bebasNeue = Bebas_Neue({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-bebas-neue',
})

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-space-grotesk',
})

export const metadata: Metadata = {
  title: "Interparts of Tulsa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${googleSansFlex.variable} ${bebasNeue.variable} ${spaceGrotesk.variable}`}>
      <body className={googleSansFlex.className}>
        <SubNav />
        <Navbar />
        {children}
      </body>
    </html>
  );
}